### ISSUE TITLE
question about bearing

### ISSUE THREAD

**Issue by zbeekman** [mwgg/GreatCircle#5]
Is the bearing the compass bearing at point A to begin the great circle/geodesic route to point B?

Is there an easy way to get compass bearings as a function of distance traveled from point A? (i.e. along the entire route, from the outset?)

Obviously any nav-guidance system could just recalculate bearing at each location as it transits the great circle, but I'm curious if your tool can provide this info at the outset.

Thanks!

**Comment by mwgg** [comment]
Hi,

The "destination" function together with bearing may be of help in your situation. You can calculate the initial bearing, use that to calculate coordinates of a point on that bearing, specific distance away, then calculate new bearing from that point. Hope this helps.
